### PR TITLE
Deployment / upgrade script for StRIF version 2

### PR DESCRIPTION
**Pull request by cybervoid0**
Ignition script which deploys StRIF second version and upgrades the contract

### CODE REVIEW

**Review by jessgusclark — COMMENTED** [review]
Why did we need to create a new file here for this? By doing that it erases the history from one version to another.

**Review by TravellerOnTheRun — CHANGES_REQUESTED** [review]
Can you explain why you've created new test file?

**Comment by cybervoid0** [comment]
The PR separates Version 1 and Version 2 StRIF contracts and tests. In the previous PR Alex wrote new functionality on top of the version 1. I restored the old version because we need both in order to upgrade old to new. Now the Repo has 2 versions of the contract and tests for both of them. And the upgrade script

**Comment by cybervoid0** [comment]
I have united tests for versions 1 and 2 into one file = deleted one extra test file

**Review by TravellerOnTheRun — APPROVED** [review]
Looks great! We may merge that in

**Pull request merged**
